#!/bin/bash

exiterr() {
	echo "-- $1. Exiting :("
	unset SSHPASS
	unset PASSWD
	exit 1
}
hpimount() {
	mkdir -p ~/hpi/$2
	sudo -E mount -t cifs -o username=$user,ip=127.0.0.1,workgroup=hpi //fs23/$1 ~/hpi/$2 || exiterr "Something went wrong while mounting the drive $1"
}
cmdexists() {
	command -v $1 &>/dev/null
	return $?
}

if [ $(mount -l|grep //fs23.*hpi/|wc -l) -gt 0 ]; then
	echo "Hpi drives are already mounted. Nothing to do."
	exit 0;
fi

if ! cmdexists mount.cifs; then
	if cmdexists yum; then
		sudo yum install cifs-utils
	elif cmdexists apt-get; then
		sudo apt-get install cifs-utils
	elif cmdexists pacman; then
		sudo pacman -S cifs-utils
	else
		exiterr "mount.cifs is missing, please install manually"
	fi
fi

if ! cmdexists sshpass; then
	if cmdexists yum; then
		sudo yum install sshpass
	elif cmdexists apt-get; then
		if ! sudo apt-get install sshpass; then
			sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
			sudo apt-get update
			sudo apt-get install sshpass
		fi
	elif cmdexists pacman; then
		sudo pacman -S sshpass
	else
		exiterr "sshpass is missing, please install manually"
	fi
fi

read -p "Enter your HPI user name: " user
read -p "Enter your HPI password: " -s PASSWD
echo ""

if ! pgrep ssh.*L139 -f &> /dev/null; then
	SSHPASS=$PASSWD
	export SSHPASS
	sudo -E sshpass -e ssh -oStrictHostKeyChecking=no -oIdentitiesOnly=yes -f -N $user@ssh-stud.hpi.uni-potsdam.de -L139:fs23:139 -L445:fs23:445 -L8080:fb10lehre:80
	unset SSHPASS
fi

# Sleep one second to wait for ssh to be ready
sleep 1

mkdir -p ~/hpi
export PASSWD
hpimount projekte$ Q
hpimount $user$ $user
hpimount lehrveranstaltungen materialien
unset PASSWD
