#!/bin/bash

exiterr() {
	echo "-- $1. Exiting :("
	exit 1
}

sudo umount ~/hpi/* &> /dev/null || exiterr "Could not unmount hpi drives"
pkill ssh.*L5139 -f
if [ $(find ~/hpi -type f |wc -l) -gt 0 ]; then
	echo "Directory hpi was not deleted because it contains files"
else
	rm -R ~/hpi
fi
